export const scenarios = [
  {
    scenarioId: "bank_fraud",
    scamType: "bank_fraud",
    fakeData: {
      bankAccount: "2244668800112233",
      upiId: "agent.collect@paybank",
      phoneNumber: "+91-9876543210",
    },
    scammerMessages: [
      "URGENT: Your bank account has been compromised. Your account will be blocked soon.",
      "To verify identity, send your OTP and account number immediately.",
      "I just resent OTP to +91-9876543210. Share it now.",
      "Confirm your account number 2244668800112233 to prevent lock.",
      "Send to UPI agent.collect@paybank and we will clear verification.",
      "Why delay? This is urgent. Reply immediately.",
      "Share branch details and account screenshot now.",
      "Last warning: account will be blocked in 2 minutes.",
      "Resending again, share OTP and account now.",
      "Final notice before lock.",
    ],
  },
  {
    scenarioId: "upi_fraud",
    scamType: "upi_fraud",
    fakeData: {
      upiId: "cashback.win@payhub",
      phoneNumber: "+91-8765432109",
    },
    scammerMessages: [
      "Congratulations! You have won cashback reward today.",
      "To claim reward, confirm your UPI verification now.",
      "Use UPI cashback.win@payhub to receive benefits.",
      "Our support line is +91-8765432109 if needed.",
      "Please share OTP to complete cashback settlement.",
      "Limited time offer, respond immediately.",
      "Quickly confirm transaction details.",
      "Pending payout. Send verification now.",
      "Last reminder for cashback release.",
      "Offer expires now.",
    ],
  },
  {
    scenarioId: "phishing",
    scamType: "phishing",
    fakeData: {
      phishingLink: "http://deal-checker.site-offer.com/claim?id=77889",
      emailAddress: "offers@deals-checker.com",
    },
    scammerMessages: [
      "You have been selected for iPhone 15 Pro giveaway.",
      "Claim now: http://deal-checker.site-offer.com/claim?id=77889",
      "If link fails, contact offers@deals-checker.com",
      "Complete verification quickly to avoid cancellation.",
      "Your reward is reserved only for today.",
      "Confirm your details and proceed.",
      "Do not share this with anyone.",
      "Time is running out, claim now.",
      "Final chance to unlock your reward.",
      "Offer closed if no response.",
    ],
  },
];
